# Generated by Django 3.0.4 on 2020-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='room_type',
            field=models.CharField(default='P', max_length=10),
        ),
    ]
