# Generated by Django 3.0.4 on 2020-03-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='message_type',
            field=models.TextField(default='text', max_length=20),
        ),
    ]
